### ISSUE TITLE
Unable to configure Form Recognizer Studio to access the Form Recognizer and Storage resources

### ISSUE THREAD

**Issue by vladiliescu** [newpatiente2e/Contoso-New-Patient-App#14]
Hi there, I'm trying to configure Form Recognizer Studio to access the Form Recognizer and Storage resources created by running the bicep scripts (as per the [docs](https://newpatiente2e.github.io/docs/form-recognizer-studio/create-project/), and it can't find either of them, only option is to create new resources from scratch. But then, creating new resources from scratch defeats the purpose of the bicep scripts. Can you confirm this feature is working for you? 

Not sure if it's relevant, but I'm using the WestEU location for the resources.

**Comment by gloveboxes** [comment]
hey there @vladiliescu  thanks for your feedback we are still locking in how bicep is creating the resources and the docs for this process. Cheers Dave
